export const ACTOR_ROLES = {
  MANUFACTURER: 'MANUFACTURER',
  DISTRIBUTOR:  'DISTRIBUTOR',
  PHARMACY:     'PHARMACY',
  ADMIN:        'ADMIN',
} as const

export const BATCH_STATUS = {
  MANUFACTURED:     'MANUFACTURED',
  WITH_DISTRIBUTOR: 'WITH_DISTRIBUTOR',
  WITH_PHARMACY:    'WITH_PHARMACY',
  PARTIALLY_SOLD:   'PARTIALLY_SOLD',
  FULLY_SOLD:       'FULLY_SOLD',
} as const

export const EVENT_TYPES = {
  MANUFACTURED:         'MANUFACTURED',
  DISTRIBUTOR_RECEIVED: 'DISTRIBUTOR_RECEIVED',
  PHARMACY_RECEIVED:    'PHARMACY_RECEIVED',
  SOLD:                 'SOLD',
} as const

export const VERDICT = {
  AUTHENTIC:    'AUTHENTIC',
  EXPIRED:      'EXPIRED',
  COUNTERFEIT:  'COUNTERFEIT',
  UNREGISTERED: 'UNREGISTERED',
} as const

export const COUNTERFEIT_REPORT_THRESHOLD = 3

export const VERIFY_CACHE_TTL = 300

export const TABLETS_PER_STRIP = 10

export const NONCE_EXPIRY_MINUTES = 10
